#!/bin/bash

gcc -Wall -Wno-format-overflow -Wno-format-truncation -o prog prog.c
if [ $? -ne 0 ]; then
  echo ABORT
  exit
fi

# play "ready for transcript"
#    echo ready > ready.txt
#    ../text_to_speech/synthesize_file --text ready.txt 
#    mv output.raw ready.wav
aplay ready.wav

# get transcript using livecaption
transcript=`../speech_to_text/mic | ../speech_to_text/livecaption |  awk -F'"' '{ print $2 }'`
#transcript="collatz conjecture"
echo "TRANSCRIPT = '$transcript'"

# run program that will:
#   perform google customsearch of  www.en.wikipedia.org/*
#   extract the best match url from the result
#   if the scrape file does not exist
#     run beautifulsoup web scraper on the url
#   endif
#   read the scrape file, and extract title and intro paragraph
#   play the title 
#   play the intro paragraph
./prog "$transcript"
