
apa102_test: apa102_test.c apa102.c apa102.h
	gcc -Wall -I. -I../../../common/include -lm -o apa102_test \
            apa102_test.c \
            apa102.c \
            ../../../common/util/misc.c

clean:
	rm apa102_test
